import './address'
import './auth'
import { builder } from './builder'
import './contact'
import './email-setting'
import './filter'
import './image'
import './import'
import './notification'
import './order'
import './page'
import './post'
import './school'
import './setting'
import './social'
import './stats'
import './upload'
import './user'
import './user-role'

export const schema = builder.toSchema()
