import './address'
import './auth'
import { builder } from './builder'
import './contact'
import './image'
import './order'
import './page'
import './school'
import './setting'
import './stats'
import './upload'
import './user'
import './user-role'

export const schema = builder.toSchema()
